DROP EVENT age_update;

CREATE EVENT
IF NOT EXISTS age_update
ON SCHEDULE EVERY 1 Day
STARTS CURRENT_TIMESTAMP
DO
UPDATE DRDB.Child 
    set Age = DATEDIFF(CURDATE(), DoB);



SELECT *
FROM information_schema.EVENTS
