

SELECT     pnb_drdb.Lab.LabName,     pnb_drdb.Schedule.Status,     COUNT(distinct pnb_drdb.Appointment.id) AS NumberOfParticipants FROM     pnb_drdb.Appointment     INNER JOIN pnb_drdb.Schedule ON pnb_drdb.Appointment.FK_Schedule = pnb_drdb.Schedule.id     INNER JOIN pnb_drdb.Study ON pnb_drdb.Appointment.FK_Study = pnb_drdb.Study.id     INNER JOIN pnb_drdb.Lab ON pnb_drdb.Study.FK_Lab = pnb_drdb.Lab.id     INNER JOIN pnb_drdb.Family ON pnb_drdb.Schedule.FK_Family = pnb_drdb.Family.id WHERE     pnb_drdb.Schedule.createdAt > '2021-01-01'     AND pnb_drdb.Family.TrainingSet = 0 GROUP BY pnb_drdb.Study.FK_Lab,     pnb_drdb.Schedule.Status;  

-- number of participants per lab   

SELECT     pnb_drdb.Lab.LabName,     pnb_drdb.Schedule.Status,     COUNT(DISTINCT pnb_drdb.Appointment.id) AS NumberOfParticipants FROM     pnb_drdb.Appointment     INNER JOIN pnb_drdb.Schedule ON pnb_drdb.Appointment.FK_Schedule = pnb_drdb.Schedule.id     INNER JOIN pnb_drdb.Study ON pnb_drdb.Appointment.FK_Study = pnb_drdb.Study.id     INNER JOIN pnb_drdb.Lab ON pnb_drdb.Study.FK_Lab = pnb_drdb.Lab.id     INNER JOIN pnb_drdb.Family ON pnb_drdb.Schedule.FK_Family = pnb_drdb.Family.id WHERE     pnb_drdb.Schedule.createdAt > '2021-01-01'     AND pnb_drdb.Family.TrainingSet = 0 GROUP BY pnb_drdb.Study.FK_Lab,     pnb_drdb.Schedule.Status;  

-- number of participants studies of each month   

SELECT     YEAR(pnb_drdb.Schedule.AppointmentTime) AS Year,     DATE_FORMAT(pnb_drdb.Schedule.AppointmentTime, '%b') AS Month,     DATE_FORMAT(pnb_drdb.Schedule.AppointmentTime, '%b 1 %Y') AS YearMonth,     COUNT(DISTINCT pnb_drdb.Appointment.id) AS NumberOfParticipants FROM     pnb_drdb.Appointment     INNER JOIN pnb_drdb.Schedule ON pnb_drdb.Appointment.FK_Schedule = pnb_drdb.Schedule.id     INNER JOIN pnb_drdb.Study ON pnb_drdb.Appointment.FK_Study = pnb_drdb.Study.id     INNER JOIN pnb_drdb.Lab ON pnb_drdb.Study.FK_Lab = pnb_drdb.Lab.id WHERE     pnb_drdb.Schedule.createdAt BETWEEN '2021-01-01'     AND '2024-12-31'     AND pnb_drdb.Schedule.Status = "Confirmed"     AND pnb_drdb.Lab.id = 2     AND YEAR(pnb_drdb.Schedule.AppointmentTime) > 2020 GROUP BY YEAR(pnb_drdb.Schedule.AppointmentTime),     MONTH(pnb_drdb.Schedule.AppointmentTime) ORDER BY     YEAR(pnb_drdb.Schedule.AppointmentTime),     MONTH(pnb_drdb.Schedule.AppointmentTime);  

-- number of participants for in-person studies of each weekday   

SELECT     YEAR(pnb_drdb.Schedule.AppointmentTime) AS Year,     DATE_FORMAT(pnb_drdb.Schedule.AppointmentTime, '%b') AS Month,     DATE_FORMAT(pnb_drdb.Schedule.AppointmentTime, '%a') AS weekday,     COUNT(DISTINCT pnb_drdb.Appointment.id) AS NumberOfParticipants FROM     pnb_drdb.Appointment     INNER JOIN pnb_drdb.Schedule ON pnb_drdb.Appointment.FK_Schedule = pnb_drdb.Schedule.id     INNER JOIN pnb_drdb.Study ON pnb_drdb.Appointment.FK_Study = pnb_drdb.Study.id     INNER JOIN pnb_drdb.Lab ON pnb_drdb.Study.FK_Lab = pnb_drdb.Lab.id WHERE     pnb_drdb.Schedule.createdAt > '2021-01-01'     AND pnb_drdb.Schedule.Status = "Confirmed"     AND pnb_drdb.Lab.id = 2     AND YEAR(pnb_drdb.Schedule.AppointmentTime) > 2020 GROUP BY YEAR(pnb_drdb.Schedule.AppointmentTime),     MONTH(pnb_drdb.Schedule.AppointmentTime),     DAYOFWEEK(pnb_drdb.Schedule.AppointmentTime) ORDER BY     DAYOFWEEK(pnb_drdb.Schedule.AppointmentTime);  

-- number of participants recruited by each personnel   

SELECT     pnb_drdb.Study.StudyName,     pnb_drdb.Personnel.Name as RecruitedBy,     pnb_drdb.Schedule.Status,     COUNT(DISTINCT pnb_drdb.Appointment.id) AS NumberOfParticipants FROM     pnb_drdb.Appointment     INNER JOIN pnb_drdb.Schedule ON pnb_drdb.Appointment.FK_Schedule = pnb_drdb.Schedule.id     INNER JOIN pnb_drdb.Personnel ON pnb_drdb.Schedule.ScheduledBy = pnb_drdb.Personnel.id     INNER JOIN pnb_drdb.Study ON pnb_drdb.Appointment.FK_Study = pnb_drdb.Study.id     INNER JOIN pnb_drdb.Lab ON pnb_drdb.Study.FK_Lab = pnb_drdb.Lab.id     INNER JOIN pnb_drdb.Family ON pnb_drdb.Schedule.FK_Family = pnb_drdb.Family.id WHERE     pnb_drdb.Study.id = 217     AND pnb_drdb.Family.TrainingSet = 0 GROUP BY ScheduledBy,     pnb_drdb.Schedule.Status;  

-- number of participants recruited by each personnel   

SELECT     pnb_drdb.Study.StudyName,     pnb_drdb.Personnel.Name as RecruitedBy,     COUNT(         DISTINCT CASE             WHEN pnb_drdb.Schedule.Status = 'Confirmed' THEN pnb_drdb.Appointment.id         END     ) AS ConfirmedParticipants,     COUNT(         DISTINCT CASE             WHEN pnb_drdb.Schedule.Status = 'Rescheduling' THEN pnb_drdb.Appointment.id         END     ) AS PendingParticipants,     COUNT(         DISTINCT CASE             WHEN pnb_drdb.Schedule.Status = 'Cancelled' THEN pnb_drdb.Appointment.id         END     ) AS CancelledParticipants,     COUNT(         DISTINCT CASE             WHEN pnb_drdb.Schedule.Status = 'Rejected' THEN pnb_drdb.Appointment.id         END     ) AS RejectedParticipants,     COUNT(DISTINCT pnb_drdb.Appointment.id) AS TotalParticipants FROM     pnb_drdb.Appointment     INNER JOIN pnb_drdb.Schedule ON pnb_drdb.Appointment.FK_Schedule = pnb_drdb.Schedule.id     INNER JOIN pnb_drdb.Personnel ON pnb_drdb.Schedule.ScheduledBy = pnb_drdb.Personnel.id     INNER JOIN pnb_drdb.Study ON pnb_drdb.Appointment.FK_Study = pnb_drdb.Study.id     INNER JOIN pnb_drdb.Lab ON pnb_drdb.Study.FK_Lab = pnb_drdb.Lab.id     INNER JOIN pnb_drdb.Family ON pnb_drdb.Schedule.FK_Family = pnb_drdb.Family.id WHERE     pnb_drdb.Study.id = 217     AND pnb_drdb.Family.TrainingSet = 0 GROUP BY pnb_drdb.Study.StudyName,     pnb_drdb.Personnel.Name;  

-- number of participants ran as assistant experimenter   

SELECT     pnb_drdb.Study.StudyName,     PrimaryExperimenter.Name as PrimaryExperimenter,     COUNT(DISTINCT pnb_drdb.Appointment.id) AS NumberOfParticipants FROM     pnb_drdb.Appointment     JOIN pnb_drdb.ExperimenterAssignment ON pnb_drdb.Appointment.id = pnb_drdb.ExperimenterAssignment.FK_Appointment     JOIN pnb_drdb.Personnel AS PrimaryExperimenter ON pnb_drdb.ExperimenterAssignment.FK_Experimenter = PrimaryExperimenter.id     INNER JOIN pnb_drdb.Schedule ON pnb_drdb.Appointment.FK_Schedule = pnb_drdb.Schedule.id     INNER JOIN pnb_drdb.Personnel ON pnb_drdb.Schedule.ScheduledBy = pnb_drdb.Personnel.id     INNER JOIN pnb_drdb.Study ON pnb_drdb.Appointment.FK_Study = pnb_drdb.Study.id     INNER JOIN pnb_drdb.Lab ON pnb_drdb.Study.FK_Lab = pnb_drdb.Lab.id     INNER JOIN pnb_drdb.Family ON pnb_drdb.Schedule.FK_Family = pnb_drdb.Family.id WHERE     pnb_drdb.Study.id = 217     AND pnb_drdb.Family.TrainingSet = 0     AND pnb_drdb.Schedule.Status = 'Confirmed'  GROUP BY     PrimaryExperimenter.Name,     pnb_drdb.Schedule.Status;  

-- number of participants ran as assistant experimenter   

SELECT     pnb_drdb.Study.StudyName,     AssistantExperimenter.Name as AssistantExperimenter,     COUNT(DISTINCT pnb_drdb.Appointment.id) AS NumberOfParticipants FROM     pnb_drdb.Appointment     INNER JOIN pnb_drdb.ExperimenterAssignment ON pnb_drdb.Appointment.id = pnb_drdb.ExperimenterAssignment.FK_Appointment     INNER JOIN pnb_drdb.Personnel AS PrimaryExperimenter ON pnb_drdb.ExperimenterAssignment.FK_Experimenter = PrimaryExperimenter.id     INNER JOIN pnb_drdb.SecondExperimenterAssignment ON pnb_drdb.Appointment.id = pnb_drdb.SecondExperimenterAssignment.FK_Appointment     INNER JOIN pnb_drdb.Personnel AS AssistantExperimenter ON pnb_drdb.SecondExperimenterAssignment.FK_Experimenter = AssistantExperimenter.id     INNER JOIN pnb_drdb.Schedule ON pnb_drdb.Appointment.FK_Schedule = pnb_drdb.Schedule.id     INNER JOIN pnb_drdb.Personnel ON pnb_drdb.Schedule.ScheduledBy = pnb_drdb.Personnel.id     INNER JOIN pnb_drdb.Study ON pnb_drdb.Appointment.FK_Study = pnb_drdb.Study.id     INNER JOIN pnb_drdb.Lab ON pnb_drdb.Study.FK_Lab = pnb_drdb.Lab.id     INNER JOIN pnb_drdb.Family ON pnb_drdb.Schedule.FK_Family = pnb_drdb.Family.id WHERE     pnb_drdb.Study.id = 217     AND pnb_drdb.Family.TrainingSet = 0     AND pnb_drdb.Schedule.Status = 'Confirmed'  GROUP BY     AssistantExperimenter.Name,     pnb_drdb.Schedule.Status;  

-- number of participants per year, month, study type   

SELECT     YEAR(pnb_drdb.Schedule.AppointmentTime) AS Year,     DATE_FORMAT(pnb_drdb.Schedule.AppointmentTime, '%b') AS Month,     DATE_FORMAT(pnb_drdb.Schedule.AppointmentTime, '%b 1 %Y') AS YearMonth,     pnb_drdb.Study.StudyType AS StudyType,     COUNT(DISTINCT pnb_drdb.Appointment.id) AS NumberOfParticipants FROM     pnb_drdb.Appointment     INNER JOIN pnb_drdb.Schedule ON pnb_drdb.Appointment.FK_Schedule = pnb_drdb.Schedule.id     INNER JOIN pnb_drdb.Study ON pnb_drdb.Appointment.FK_Study = pnb_drdb.Study.id     INNER JOIN pnb_drdb.Lab ON pnb_drdb.Study.FK_Lab = pnb_drdb.Lab.id     INNER JOIN pnb_drdb.Family ON pnb_drdb.Schedule.FK_Family = pnb_drdb.Family.id WHERE     pnb_drdb.Schedule.createdAt > '2021-01-01'     AND pnb_drdb.Schedule.Status = 'Confirmed'     AND pnb_drdb.Lab.id = 2     AND YEAR(pnb_drdb.Schedule.AppointmentTime) > 2020     AND pnb_drdb.Family.TrainingSet = 0   GROUP BY YearMonth,     Year,     Month,     StudyType ORDER BY     Year,     Month;  

SELECT     YEAR($ { { DBName } }.Schedule.AppointmentTime) AS Year,     DATE_FORMAT($ { { DBName } }.Schedule.AppointmentTime, '%b') AS Month,     DATE_FORMAT($ { { DBName } }.Schedule.AppointmentTime, '%a') AS weekday,     COUNT($ { { DBName } }.Appointment.id) AS NumberOfParticipants FROM     $ { { DBName } }.Appointment     INNER JOIN $ { { DBName } }.Schedule ON $ { { DBName } }.Appointment.FK_Schedule = $ { { DBName } }.Schedule.id     INNER JOIN $ { { DBName } }.Study ON $ { { DBName } }.Appointment.FK_Study = $ { { DBName } }.Study.id     INNER JOIN $ { { DBName } }.Lab ON $ { { DBName } }.Study.FK_Lab = $ { { DBName } }.Lab.id     INNER JOIN pnb_drdb.Family ON pnb_drdb.Schedule.FK_Family = pnb_drdb.Family.id WHERE     pnb_drdb.Schedule.createdAt > '2021-01-01'     AND pnb_drdb.Schedule.Status = 'Confirmed'     AND pnb_drdb.Lab.id = 2     AND YEAR(pnb_drdb.Schedule.AppointmentTime) > 2020     AND pnb_drdb.Family.TrainingSet = 0  GROUP BY     weekday,     Year,     Month ORDER BY     Year,     Month,     weekday;