const Sequelize = require('sequelize');

const sequelize = new Sequelize("DRDB_FAKE", "root", "", {
  host: "localhost",
  dialect: "mysql",
  logging: false,
});

async function run() {
  try {
    await sequelize.authenticate();
    console.log('Connection has been established successfully.');

    // Get a few active families, children, and studies
    const [families] = await sequelize.query('SELECT id FROM Family LIMIT 10');
    const [children] = await sequelize.query('SELECT id, FK_Family FROM Child WHERE FK_Family IS NOT NULL LIMIT 10');
    const [personnel] = await sequelize.query('SELECT id FROM Personnel WHERE Role = "Admin" LIMIT 1');
    const [studies] = await sequelize.query('SELECT id FROM Study LIMIT 5');

    if (!families.length || !children.length || !personnel.length || !studies.length) {
      console.log('Not enough data to create schedules.');
      return;
    }

    const scheduledById = personnel[0].id;

    for (let i = 1; i <= 5; i++) {
      const child = children[Math.floor(Math.random() * children.length)];
      const familyId = child.FK_Family;
      const studyId = studies[Math.floor(Math.random() * studies.length)].id;

      // AppointmentTime next few days
      const appointmentDate = new Date();
      appointmentDate.setDate(appointmentDate.getDate() + i);
      appointmentDate.setHours(10 + i, 0, 0, 0); // Randomize times a bit (11am, 12pm, etc.)

      // Insert Schedule
      const [scheduleResult] = await sequelize.query(`
        INSERT INTO Schedule (AppointmentTime, Status, Reminded, ThankYouEmail, Note, ScheduledBy, FK_Family, Completed)
        VALUES (?, 'Confirmed', 0, 0, 'Autogenerated fake schedule', ?, ?, 0)
      `, {
        replacements: [appointmentDate, scheduledById, familyId]
      });

      const scheduleId = scheduleResult;

      // Insert Appointment
      await sequelize.query(`
        INSERT INTO Appointment (FK_Study, FK_Family, FK_Child, FK_Schedule)
        VALUES (?, ?, ?, ?)
      `, {
        replacements: [studyId, familyId, child.id, scheduleId]
      });

      console.log(`Successfully created Schedule ${scheduleId} for Study ${studyId} on ${appointmentDate.toLocaleDateString()}`);
    }

  } catch (error) {
    console.error('Unable to add fake schedules:', error);
  } finally {
    await sequelize.close();
  }
}

run();
